Advanced Segment Anything Model
HumanSignal/label-studio-ml-backend pull request #304
Opened 2023-07-26 05:15 UTC by shondle

https://github.com/shondle/label-studio-ml-backend/assets/106922533/42a8a535-167c-404a-96bd-c2e2382df99a

New SAM update. Lots of new features, and added a new model for higher accessibility for people without access to higher-end compute resources to load SAM.

This adds a new prediction backend I am calling Advanced SAM. This allows many more options for adjusting annotation predictions than before with the ONNX models, and includes [a video tutorial](https://drive.google.com/file/d/1OMV1qLHc0yYRachPPb8et7dUBjxUsmR1/view?usp=sharing) to help those getting started. 

## Advanced SAM Features

*Adjusting Regions With Multiple Input Prompts At A Time*
- :fire:  Combine multiple keypoints and a rectangle label together to fine-adjust areas of region predictions. 
- :fire: Combine negative keypoints with other smart tools to tell the model where to avoid when generating predictions.
- :fire: Unlimited keypoints allowed for generating predictions for each region, allowing ultimate customizability and time saved for annotators!
- :fire: Move around the current smart keypoint or rectangle label for the current region and watch as predictions are adjusted real-time!

*Model Predictions*
- :fire: Choose to use the SAM architecture from Facebook or run a lighter version of SAM from the MobileSAM paper. I am able to run this **and receive predictions :boom: in <1s on my Laptop GPU (RTX 3060)!**:boom: I record the entire video tutorial on my laptop while gathering predictions real-time.

## ONNX SAM Features

*Features*
- Added ability to use smart rectangle labels to generate predictions

*Issues Addressed*
- ONNX image predictions offset issue addressed in README. This was due to the need to specify image size before generating the model. #278 
- Video tutorial to show how to use the backend (should address some of the no kwargs received issues). #287 

TL;DR: Use the AdvancedSAM backend to batch together a rectangle label, and unlimited positive and negative keypoints to fine-adjust model predictions and see model predictions change real-time while annotating. Use the MobileSAM architecture to run predictions on consumer hardware. Video tutorial included to help people get started.

2023-07-27 00:42 UTC, hogepodge commented
This LGTM, and it's a great update to the model. Thanks @shondle!

2023-07-27 07:55 UTC, niklub requested changes

2023-07-27 07:55 UTC, niklub commented on label_studio_ml/examples/segment_anything_model/advanced_sam.py
> +        global PREV_IMG_PATH
I'm not sure this gonna work with concurrent requests

2023-07-27 07:55 UTC, niklub commented on label_studio_ml/examples/segment_anything_model/advanced_sam.py
> +    def fit(self, completions, workdir=None, **kwargs):
Could you please remove this function? The interface was reworked in the latest base branch and no longer compatible with this signature

2023-07-27 07:58 UTC, niklub commented
That's excellent @shondle ! Let's slightly modify the code to make it fully compatible with the new ML backend codebase, I'll follow up with other changes to be made quite soon. Thank you!

2023-07-30 20:54 UTC, botcs commented on label_studio_ml/examples/segment_anything_model/advanced_sam.py
> +    from mobile_sam import SamPredictor, sam_model_registry
This file is missing at the moment from the PR and the original version

2023-08-08 17:08 UTC, hogepodge commented
@niklub @shondle any updates on the progress of this? We've got a lot of interest, and I'd like to move forward on getting this merged

2023-08-08 17:15 UTC, hogepodge commented on label_studio_ml/examples/segment_anything_model/Dockerfile
I'd like for a few things to be adjusted. First, a secret is being leaked into the Dockerfile in an environment variable. In my own testing, this actually does nothing. However, with some minor modifications it's possible to use Label Studio as an image source. If the user sets the variables:

```
ACCESS_TOKEN=<token>
LABEL_STUDIO_HOST=<ls_host_ip>
```

Loads those environment variables into the model:

```
ACCESS_TOKEN = os.environ.get("ACCESS_TOKEN", None)
LABEL_STUDIO_HOST = os.environ.get("LABEL_STUDIO_HOST", None)
```

and updates the load image code

```
from label_studio_tools.core.utils.io import get_local_path
...
image_path = get_local_path(img_path, access_token=ACCESS_TOKEN, hostname=LABEL_STUDIO_HOST)
```

Label Studio can be used to host the images.

2023-08-09 11:48 UTC, niklub commented
> @niklub @shondle any updates on the progress of this? We've got a lot of interest, and I'd like to move forward on getting this merged

I'm merging it to the base branch now to continue adjusting with the new ML backend interface. @shondle @hogepodge I'll let you know when it is done and your review is needed

2023-08-09 11:48 UTC, merged